## trye=>
#### tryexcept
tryexcept method
```
try:
  print(x)
except:
  print('An exception occurred')
```